"""add_server_default_to_poll_edit_history_edited_at

Revision ID: e7d87686b4d9
Revises: 0f7532c628f1
Create Date: 2025-05-10 14:37:18.902527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision: str = 'e7d87686b4d9'
down_revision: Union[str, None] = '0f7532c628f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll_edit_history', 'edited_at',
           existing_type=sa.DateTime(timezone=True),
           server_default=func.now(),
           nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll_edit_history', 'edited_at',
           existing_type=sa.DateTime(timezone=True),
           server_default=None,
           nullable=False)
    # ### end Alembic commands ###
